Endpoints firebase
la-venganza/ubademy-back pull request #11
Opened 2021-10-31 19:24 UTC by German-Rotili

2021-10-31 20:47 UTC, agscontini commented on app/firebase.js
> +   } catch (e) {
Esto no devuelve una excepción particular si falla la autenticación por unauthorized?  ejemplo, si el servicio esta inaccesible vs fallo la autenticación?

2021-10-31 20:47 UTC, agscontini commented on app/src/routes/course.js
> +    }
acá separaría el posible error que pueda venir por el fallo de autenticación..para ese devolvería un unauthorized (403) y después contemplaría los errores que puedan venir por la pegada al back de python..si no esta disponible un 500 hablando de error de server...o si hay algún problema no esperado (request inválido por no tener algún campo obligatorio...mandar a crear un curso por alguien que no es user, etc) 
Por otro lado, el endpoint del bakc de python ya existe, en el nuevo pr se sumo todo para que tenga la entidad de un curso real, pero ya tenes el básico sobre /api/v1/courses/

2021-10-31 20:47 UTC, agscontini commented on app/src/routes/course.js
> +            "description": 'Descripcion re copada',
acá faltaría el user_id..lo que me hace pensar que (voy a corregir sobre el pr actual) lo mejor sería
{
  "user_id" : "kdjflasj",
   "course" : {
        ...
   }
}

(hoy no esta separado el course en el objeto de creación)

2021-10-31 20:47 UTC, agscontini commented on app/src/routes/course.js
> +    } catch (e) {
idem sobre la creación

2021-10-31 20:47 UTC, agscontini commented on app/src/routes/user.js
> +        body = {
el back de python ya tiene esto para que le puedas pegar

2021-10-31 20:47 UTC, agscontini commented on app/src/routes/user.js
> +    } catch (e) {
idem comentario de la creación de cursos

2021-10-31 20:47 UTC, agscontini commented on app/src/routes/user.js
> +        // Send to back
ya esta esto en el back de python para que se le pueda pegar tmb.

2021-10-31 20:47 UTC, agscontini commented on app/src/routes/user.js
> +    } catch (e) {
idem arriba sobre manejo de errores entre auth y los que puedan venir del back

2021-10-31 20:47 UTC, agscontini commented on app/swagger.json
> +        "/course": {
sumaría los unauthorized al swagger por la autenticación.

2021-10-31 20:55 UTC, agscontini commented on app/src/routes/course.js
> +            "description": 'Descripcion re copada',
Me corrijo, ahi vi porque estaba como estaba :P 
es tipo el body que vos estas pasando (no separado el user_id del course) pero tenes que sumar el campo creator_id que es el "dueño"/creador/profesor del curso

2021-10-31 21:43 UTC, recheconea commented on app/firebase.js
> +   } catch (e) {
Si, y estaria bueno distinguirlo.

2021-10-31 21:43 UTC, recheconea commented on app/src/routes/course.js
> +    }
+1

2021-10-31 21:44 UTC, recheconea commented on app/src/routes/course.js
> +            "description": 'Descripcion re copada',
Me meto aca, +1 a creator id. Y luego los campos que hagan falta. Yo pase una lista minima de los que estoy usando en el diseno actual pero eso deberia ir mutando con el tiempo.

2021-10-31 21:45 UTC, recheconea commented on app/src/routes/course.js
> +    } catch (e) {
Aca necesito si o si que me devuelvas idealmente todo, pero de minima el id del curso creado para poder hacer un potencial update.

2021-10-31 21:49 UTC, recheconea requested changes

2021-10-31 21:49 UTC, recheconea commented on app/firebase.js
> +let auth = firebaseAuth.getAuth(app);
Si no muta el valor, mandale const

2021-10-31 21:49 UTC, recheconea commented on app/src/middlewares/cookieHandler.js
> +function getcookie(req) {
Aca @Luciana123 capaz puede echar mas luz sobre el asunto, peor entiendo que teniamos algun handler de cookies agregado.

2021-10-31 21:49 UTC, recheconea commented on app/src/routes/course.js
> +        let cookies = getcookie(req)
Idem arriba, let solo si vamos a cambiar valores.

2021-10-31 21:49 UTC, recheconea commented on app/src/routes/course.js
> +        body = {
Este body no lo veo declarado, de no estarlo, agregale un const adelante

2021-10-31 23:36 UTC, German-Rotili commented on app/firebase.js
> +   } catch (e) {
La verdad que no hay mucho en la docu, pero capaz esta mas escondido. Puedo ver de armar algo yo de ultima

2021-11-01 00:51 UTC, Luciana123 commented on app/src/middlewares/cookieHandler.js
> +function getcookie(req) {
teníamos el cookieSession, que lo usaba en conjunto con el passportJS, pero habría que ver cómo usarlo bien para nuestro caso de uso nuevo.

2021-11-02 03:04 UTC, German-Rotili commented on app/swagger.json
> +        "/course": {
Esto falta, despues lo deino bien para el prox pr

2021-11-02 14:36 UTC, recheconea requested changes

2021-11-02 14:36 UTC, recheconea commented on app/app.js
> +// const cookieSession = require('cookie-session');
Habria que sacar el comment

2021-11-02 14:36 UTC, recheconea commented on app/src/middlewares/firebase.js
> +    console.log(Date.now())
Ojo el console log

2021-11-02 14:36 UTC, recheconea commented on app/src/routes/user.js
> +        console.log(req.params.id);
ojo el console log

2021-11-02 14:36 UTC, recheconea commented on app/src/routes/user.js
> +        let body = {
const seria mas apropiado

2021-11-02 15:59 UTC, agscontini commented on app/src/errors/authError.js
> +        this.message = 'Error authenticating against Firebase'
una pavada, pero le sacaría a la clase authError el dato de contra quien falló la autenticación.
Pondría algo como 'Error authenticating against authenticator entity' o server

2021-11-02 15:59 UTC, agscontini commented on app/src/errors/connecionError.js
> +        this.message = 'Error connecting to Python service'
Idem arriba...quizás '...to server'
Más que nada porque los errores son generales y se podrían aplicar a otro server sin problema. El que hace el llamado es el que sabe a quien le esta pegando, la clase error no

2021-11-02 15:59 UTC, agscontini commented on app/src/errors/authError.js
> +        this.message = 'Error authenticating against Firebase'
Incluso si querés ser más descriptivo, podes recibir en el constructor y pasarle el dato de contra quien es, y sumarlo al mensaje desde ahi

2021-11-02 15:59 UTC, agscontini commented on app/src/errors/connecionError.js
> +        this.message = 'Error connecting to Python service'
idem sugerencia del constructor o simil del auth para hacer el mensaje más descriptivo

2021-11-02 16:04 UTC, agscontini commented on app/src/routes/course.js
> +        if (e instanceof ConnectionError) {
esto, no se si en node se puede, o si es muy complicado, pero como idea. Se puede lanzar la excepcion puntual y tener un handler que intercepte las respuestas del server y, por ejemplo, capturas las ConnectionError y ahi das el res.status(500).send(body) con el body construido (podría ser un objeto error response o algo asi que tiene error y message por constructor y te da el body.
De esta froma cuando te encontrás un conecctionError o un AuthError u otro, lo lanzas nomás y lo interceptas previo a la respuesta del server y das el response asociado a cada tipo de error.
(y podes tener un catch brusco como último en prioridad que agarra todo lo que no contemplaste y te devuelve un 500 con un mensaje más general de que algo raro paso :P )
Ni lo digo para hacerlo porque tampoco se que tan heavy sería, pero como idea de última para tener en cuenta

2021-11-03 01:00 UTC, German-Rotili commented on app/src/routes/course.js
> +        if (e instanceof ConnectionError) {
Lo veo para un proximo refactor. Pero por ahora me parece que anda bien.

2021-11-03 01:01 UTC, merged