Refactor
la-venganza/ubademy-back pull request #14
Opened 2021-11-07 22:35 UTC by German-Rotili

2021-11-07 22:39 UTC, agscontini commented on app/src/middlewares/requestMapper.js
> +    stages.forEach(element => {
pregunta pava..hay algo que valide que stages tenga algo? o sea, que pasa si te mandan sin stages...esto corre o explota? O ya se valida al recibir el request que se cumpla todo lo obligatorio?

2021-11-07 22:41 UTC, German-Rotili commented on app/src/middlewares/requestMapper.js
> +    stages.forEach(element => {
Se puede crea un course sin stages?

2021-11-07 22:44 UTC, German-Rotili commented on app/src/middlewares/requestMapper.js
> +    stages.forEach(element => {
Se puede crea un course sin stages? Porque si solo se puede cdrear con un stage por lo menos. Entonces rompe y tira error.

2021-11-07 22:45 UTC, agscontini commented on app/src/middlewares/requestMapper.js
> +    stages.forEach(element => {
entiendo que no, pero justamente por eso tenes que verificar que hayan y en caso de que no hayan devolver bad request...
idem si te pegan con una lesson que tiene examen..el examen tiene que tener alguna pregunta, etc

2021-11-07 22:46 UTC, German-Rotili commented on app/src/middlewares/requestMapper.js
> +    stages.forEach(element => {
Ahora romperia y devolveria, no bad request pero si algun otro. Se puede incorporar

2021-11-07 22:48 UTC, agscontini commented on app/src/middlewares/requestMapper.js
> +    stages.forEach(element => {
hay bastantes validaciones que se deberían hacer en la api, antes de decidir propagar el request al back de python. Porque se supone que cada api tiene sus requerimientos mínimos para que el request sea válido. Sino tenés que interpretar la respuesta de error que te da el back de python, y después ver como querés devolver eso y se vuelve mucho más complicado manejar el error y el mensaje.

2021-11-07 23:00 UTC, agscontini commented on app/src/middlewares/requestMapper.js
> +    stages.forEach(element => {
claro...romper con que hubo un null pointer o simil node, no esta bueno, porque el que te consume no entiende que paso y que falló con el request. no le da flexibilidad ni forma de meter en el front un mensaje claro de que problema hubo. Onda, el front también tiene sus validaciones, pero cada capa tiene que tener las suyas

2021-11-07 23:57 UTC, agscontini reviewed
No me queda claro el manejo de los errores del back de python. Por ejemplo: si queres editar un curso y no sos el creador/profesor, el back te va a devolver un 403 forebidden... ahi que le devolves al front para que sepa hay un tema de permisos?
Si es un error de que no existe el usuario, o algún not found, que le estas devolviendo al front para que interprete eso?

2021-11-08 00:01 UTC, recheconea requested changes

2021-11-08 00:01 UTC, recheconea commented on app/src/middlewares/requestMapper.js
> +const ServerError = require("../errors/serverError")
Ojo, esto NO es un middleware, es un util

2021-11-08 00:01 UTC, recheconea commented on app/src/middlewares/requestMapper.js
> +    if (typeof stages == 'undefined' || !Array.isArray(stages)) {
===

2021-11-08 00:01 UTC, recheconea commented on app/src/routes/course.js
> +        const response = await pythonBackendService.getCourses()
Fijate el nombre de este servicio, seguramente courseService seria mas idoneo

2021-11-08 00:15 UTC, agscontini commented on app/src/middlewares/userService.js
> +        const res = await instance.patch('/api/v1/courses/' + id, body)
ojo que acá estas haciendo un update del curso cuando queres updatear un user

2021-11-08 01:45 UTC, German-Rotili commented
> No me queda claro el manejo de los errores del back de python. Por ejemplo: si queres editar un curso y no sos el creador/profesor, el back te va a devolver un 403 forebidden... ahi que le devolves al front para que sepa hay un tema de permisos? Si es un error de que no existe el usuario, o algún not found, que le estas devolviendo al front para que interprete eso?

Ahi le agregue un resolver del status que llega del back-py, de esta forma tira el mismo status, lo mete todo en ServerError, para que se sepa que viene por problema del back-py y con el mensaje se deberia eliminar cualquier ambiguedad que quede.

2021-11-08 02:37 UTC, recheconea approved these changes

2021-11-08 02:38 UTC, agscontini approved these changes

2021-11-08 02:50 UTC, merged