Swagger
la-venganza/ubademy-back pull request #3
Opened 2021-09-28 00:26 UTC by Luciana123

- agrego docs con -
-  separo servicios de app.js

2021-09-29 13:34 UTC, recheconea commented on app/package.json
> +    "sleep": "^6.3.0",
Para que es esta lib?

2021-09-29 13:35 UTC, recheconea requested changes

2021-09-29 13:35 UTC, recheconea commented on app/services.js
> +const express = require('express');
Personalmente armaria un archivo routes y cada servicio (por ejemplo auth podria ser uno) lo mandaria a un file aparte.

2021-09-29 13:35 UTC, recheconea commented
Ojo el branch, deberia apuntar a develop

2021-09-30 23:38 UTC, Luciana123 commented on app/package.json
> +    "sleep": "^6.3.0",
quedó del mock, ahí la saco

2021-09-30 23:49 UTC, merged